---
- name: Install PostgreSQL + deps
  apt:
    name: "{{ postgres_packages }}"
    state: present
    update_cache: yes

- name: Ensure PostgreSQL started & enabled
  service:
    name: "{{ postgres_service_name }}"
    state: started
    enabled: yes
- name: Ensure ACL tools are present (required for become_user)
  package:
    name: acl
    state: present
    
- name: Create DB user for SonarQube
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ sonar_db_user }}"
    password: "{{ sonar_db_password }}"
    role_attr_flags: "LOGIN"

- name: Create SonarQube database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ sonar_db_name }}"
    owner: "{{ sonar_db_user }}"
    encoding: "UTF8"
    lc_collate: "en_US.UTF-8"
    lc_ctype: "en_US.UTF-8"
    template: "template0"
